// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wokopfxvuibrxgvmeavq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indva29wZnh2dWlicnhndm1lYXZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MzU1ODQsImV4cCI6MjA1ODMxMTU4NH0.usf6DmbU6PUloxFSpJkas5VHBNE_9yaNmt-1yanAl58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);